### ISSUE TITLE
Backend-Event API

### ISSUE THREAD

**Issue by KOMATISATYA** [Event-Coordination-Engine/satya-ece#6]
- API for Event CRUD operation 
- Backend validations

**Comment by KOMATISATYA** [comment]
Working on Event API-15/08

**Comment by KOMATISATYA** [comment]
Completed the Event API with all the validations.

**Comment by yateesh-chandra-duggirala** [comment]
Commit and PR to be  attached Later.. Good to close
@KOMATISATYA
